DELETE FROM words
WHERE lektion_num = 3;

INSERT INTO words(german, hungarian, word_type_id, lektion_num) VALUES
('das Fotoalbum-s', 'fotóalbum', 0, 3), ('sprechen', 'beszélni',1, 3), ('sehen', 'látni', 1, 3), ('da', 'ott(rövid)', 4, 3), ('hässlich', 'csúnya', 3, 3), ('das', 'ő, az', 2, 3), ('eben', 'éppenséggel, épp', 4, 3), ('der Hund-e', 'kutya', 0, 3), ('schon', 'már', 4, 3), 
('verrückt', 'őrült', 3, 3), ('ja', 'igen, hiszen', 11, 3), ('umgekehrt', 'fordítva', 3, 3), ('dort', 'ott(hosszú)', 4, 3), ('die Großmutter-:', 'nagymama(hosszú)', 0, 3), ('die Oma-s', 'nagymama(rövid)', 0, 3), ('nicht mehr', 'már nem', 10, 3), ('der Onkel-', 'nagybácsi', 0, 3),
('schwerhörig', 'nagyothalló', 3, 3), ('die Frau-en', 'nő, feleség', 0, 3), ('die Tante-n', 'nagynéni', 0, 3), ('ergänzen', 'kiegészíteni', 1, 3), ('einander', 'egymást', 2, 3), ('witzig', 'vicces',3, 3), ('der Cousin-s', 'unokatestvér(fiú)', 0, 3), ('die Cousine-n', 'unokatestvér(lány)', 0, 3), ('alt', 'idős, öreg', 3, 3), ('damals', 'akkoriban', 4, 3), ('die Eltern', 'szülők', 0, 3), ('stehen', 'állni', 1, 3), ('essen', 'enni', 1, 3) ,('die Großeltern', 'nagyszülők', 0, 3), ('hungrig', 'éhes', 3, 3), ('etwas', 'valami', 2, 3), ('helfen', 'segíteni', 1, 3), ('kochen', 'főzni', 1, 3),
('lieber', 'inkább', 4, 3), ('das Brötchen-', 'zsömle', 0, 3), 
('müde', 'fáradt', 3, 3), ('egoistisch', 'egoista', 3, 3), ('geben', 'adni', 1, 3), ('das Brot-e', 'kenyér', 0, 3), ('die Butter-', 'vaj', 0, 3), ('das Essen', 'étel', 0, 3), ('der Schatz-:e', 'kincs', 0, 3), ('die Idee-n', 'ötlet', 0, 3), ('nehmen', 'venni(valamiből)', 1, 3), ('noch', 'még', 4, 3), ('der Kuchen-', 'sütemény, kalács', 0, 3), ('durstig', 'szomjas', 3, 3), ('satt', 'jóllakott', 3, 3), ('nirgendwo', 'sehol, sehol se', 4, 3), ('die Geschwister', 'testvérek', 0, 3), ('der Bruder-:', 'fiútestvér', 0, 3),('die Schwester-n', 'lánytestvér', 0, 3), ('fotogen', 'fotogén', 3, 3), 
('zeichnen', 'rajzolni', 1, 3), ('die Familie-n', 'család', 0, 3),('fleißig', 'szorgalmas', 3, 3), ('selbstlos', 'önzetlen', 3, 3),('der Muskel-s', 'izom', 0, 3), ('das Auto-s', 'autó', 0, 3), ('das Jahr-e', 'év', 0, 3), ('Wer?', 'Ki?', 2, 3),('der Sohn-:e', 'fia(vkinek)', 0, 3), ('die Tochter-:', 'lánya(vkinek)', 0, 3), ('das Leben-s', 'élet', 0, 3), ('das Album-s', 'album', 0, 3), ('Du siehst das umgekehrt', 'Fordítva nézed', 10, 3), ('Ach ja!', 'Ja igen!', 10, 3), ('Wie alt sind Sie?', 'Hány évesek?', 10, 3) , ('Spinnst du?', 'Megőrültél?', 10, 3), ('belegtes Brötchen', 'szendvics', 10, 3), ('Also gut!', 'Na jó!', 10, 3), ('Gibst du mir bitte...?', 'Ideadod kérlek a...?', 10, 3), ('Das ist eine gute Idee!', 'Ez egy jó ötlet!', 10, 3), ('Ich bin zum Bersten voll', 'Dugig tele vagyok', 10, 3), ('dein', 'tiéd', 2, 3), ('sein', 'övé(fiú)', 2, 3), ('sein', 'övé(semleges)', 2, 3), ('ihr', 'övé(lány)',2, 3), ('unser', 'miénk', 2, 3), ('euer', 'tiétek', 2, 3), ('ihr', 'övék', 2, 3), ('Ihr', 'öné/önöké', 2, 3), ('selten','ritka', 3, 3), ('häufig', 'gyakori', 3, 3), ('der Ministaat-en', 'miniállam', 0, 3), ('das Herzogtum-:er', 'hercegség', 0, 3), ('die Aptssprache-n', 'hivatalos nyelv', 0, 3), ('das Land-:er', 'ország', 0, 3), ('der Quadratkilometer-', 'négyzetkilométer', 0, 3), ('der Einwohner-', 'lakos', 0, 3), ('die Mutter-:', 'anya', 0, 3), ('die Mutter-n', 'anya(csavar)', 0, 4);
