	DELETE FROM words
	WHERE lektion_num = 4;


	INSERT INTO words (german, hungarian, word_type_id, lektion_num)
		VALUES ('die Geburtstagsparty-s', 'születésnapi parti', 1, 4), ('organisieren', 'szervezni', 1, 4), ('heute', 'ma', 4, 4),
	('der Geburtstag-e', 'születésnap', 0, 4), ('deswegen', 'ezért', 4, 4), ('aufgeregt', 'izgatott', 3, 4),
	('gelingen+D', 'sikerül vkinek vmi', 1, 4), ('laufen', 'futni', 1, 4), ('die Milch-', 'tej', 0, 4), ('der Mensch-en', 'ember', 0, 4), ('die Torte-n', 'torta', 0, 4), ('schade', 'kár (vmiért)', 3, 4), ('alles', 'minden', 2, 4), ('zu', 'túl, túlzottan', 4, 4),
	('spät', 'késő', 3, 4), ('der Gast-:e', 'vendég', 0, 4),
	 ('backen', 'sütni', 1, 4), ('die Ordnung', 'rend', 0, 4), 
	('die Zauberin-nen', 'varázslónő', 0, 4), ('der Zauber-s', 'varázslat', 0, 4), ('der Zauberer-s', 'varázsló', 0, 4), ('schmecken+D', 'ízlik vkinek vmi', 1, 4), ('ungeschickt', 'ügyetlen', 3, 4), 
	('pessimistisch', 'pesszimista', 3, 4), ('pechschwarz', 'koromfekete', 3, 4), ('merken', 'megjegyezni(magának vmit)', 1, 4), 
	('das Glas-:er', 'pohár', 0, 4), ('nie', 'soha', 4, 4), 
	('halbleer', 'félig üres', 3, 4), ('sondern', 'hanem', 7, 4),
	 ('halbvoll', 'félig teli', 3, 4), ('klingeln', 'csöngetni', 1, 4), ('öffnen', 'kinyitni', 1, 4), ('die Tür-en', 'ajtó', 0, 4), 
	('empfangen', 'fogadni vkit', 1, 4), ('erledigen', 'elintezni vmit', 1, 4), ('todmüde', 'hullafáradt', 3, 4), ('ein wenig', 'egy kicsi', 10, 4), ('der Alkohol-e', 'alkohol', 0, 4),
	 ('die Welt-en', 'világ', 0, 4), ('ganz', 'egész, teljes', 3, 4), ('anders', 'más, máshogy', 3, 4), ('der Wein-e', 'bor', 0, 4), ('für', 'számára, részére', 6, 4), ('der Champagner-', 'pezsgő', 0, 4), ('der Alkoholiker-', 'alkoholista', 0, 4), ('wissen', 'tudni', 1, 4), ('die Überraschung-en', 'meglepetés', 0, 4), ('der Bus-se', 'busz', 0, 4),
	 ('fahren', 'utazni,vezetni', 1, 4), ('klar', 'világos', 3, 4), 
	('der Tisch-e', 'asztal', 0, 4), ('hinten', 'hátul', 4, 4), 
	('das Geschenk-e', 'ajándék', 0, 4), ('schenken+D', 'ajándékozni vkinek', 1, 4), ('vorne', 'elöl', 4, 4), ('kosten', 'kerül vmibe', 1, 4), ('geldgierig', 'pénzéhes,anyagias', 3, 4), ('der Bankier-s', 'bankár', 0, 4), ('der Politiker-', 'politikus', 0, 4), 
	('Du siehst alles pechschwarz', 'Mindent koromfeketének látsz', 10, 4), ('Es klingelt', 'Csöngetnek', 10, 4), 
	('Wie geht''s?', 'Hogy vagy?', 10, 4), ('Was für eine Überraschung!', 'Micsoda meglepetés!', 10, 4), ('Du hast Verspätung', 'Késel', 10, 4), 
		('Alles klar!', 'Minden világos!', 10, 4), ('Was kostet das?', 'Mibe kerül(az)', 10, 4), ('Die Torte schmeckt nach Knoblauch', 'A torta fokhagyma ízű', 10, 4), ('geschickt', 'ügyes', 3, 4), ('die Telefonnummer-n', 'telefonszám', 0, 4), ('mir', 'nekem', 2, 4), ('dir', 'neked', 2, 4), ('ihm', 'neki(fiú)', 2, 4), ('ihr', 'neki(lány)', 2, 4), ('ihm', 'neki(semleges)', 2, 4), ('uns', 'nekünk', 2, 4), ('euch', 'nektek', 2, 4), ('ihnen', 'nekik', 2, 4), ('Ihnen', 'önnek/önöknek', 2, 4), ('der Weg-e', 'út', 0, 4), ('der Teufel-s', 'ördög', 0, 4), ('fertig', 'kész', 3, 4), ('mager', 'sovány', 3, 4), ('das Wasser-:', 'víz', 0, 4), ('nett', 'kedves', 3, 4), ('höflich', 'udvarias', 3, 4), ('goldig', 'aranyos', 3, 4), ('das Kleid-er', 'ruha', 0, 4), ('die Adresse-n', 'lakcím', 0, 4), ('das Lied-er', 'dal', 0, 4), ('blind', 'vak', 3, 4), ('die Katze-n', 'macska', 0, 4), ('der Fisch-e', 'hal', 0, 4), ('der Vogel-:', 'madár', 0, 4), ('die Zeitung-en', 'újság', 0, 4), ('die Grube-n', 'gödör', 0, 4), ('graben', 'ásni', 1, 4), ('brechen', 'törni', 1, 4), ('lesen', 'olvasni',1, 4), ('treffen', 'találkozni', 1, 4), ('sterben', 'meghalni', 1, 4), ('vergessen', 'elfelejteni', 1, 4), ('tragen', 'hordani', 1, 4), ('fangen', 'fogni', 1, 4), ('fallen', 'esni', 1, 4), ('waschen', 'mosni', 1, 4), ('schlafen', 'aludni', 1, 4), ('richtig', 'helyes', 3, 4), ('falsch', 'helytelen', 3, 4), ('die Hausaufgabe-n', 'házifeladat', 0, 4), ('die Einladung-en', 'meghívó', 0, 4), ('Bis morgen!', 'Holnap találkozunk!', 10, 4), ('feiern', 'ünnepel', 1, 4), ('die Person-en', 'személy', 0, 4), ('wie viele', 'hány, mennyi', 10, 4), ('die Zahl-en', 'szám', 0, 4), ('die Luft', 'levegő', 0, 4), ('hoffen', 'remélni', 1, 4), ('lang', 'hosszú', 3, 4), ('kurz', 'rövid', 3, 4), ('der Soldat-en', 'katona', 0, 4), ('der Tischler-en', 'asztalos', 0, 4), ('der Sportler-s','sportoló', 0, 4), ('werden', 'lesz, válik vmivé', 1, 4), ('die Suppe-n', 'leves', 0, 4), ('die Wahrheit-en', 'igazság, valóság', 0, 4), ('das Huhn-:er', 'csirke', 0, 4), ('die Lösung-en', 'vminek a megoldása', 0, 4), ('die Quelle-n', 'forrás(víz,műforrás)', 0, 4), ('überhaupt', 'egyáltalán', 4, 4), ('davon', 'erről', 4, 4), ('die Nachricht-en', 'hír', 0, 4), ('die Ursache-n', 'kiváltó ok', 0, 4), ('der Grund-:e', 'politikai ok, indíték', 0, 4), ('das Fundbüro-s', 'talált tárgyak osztálya', 0, 4), ('das Handy-s', 'mobiltelefon', 0, 4), ('hören', 'hallani', 1, 4), ('wichtig', 'fontos', 3, 4), ('verlieren', 'veszíteni', 1, 4), ('der Zug-:e', 'vonat', 0, 4), ('etwas trinken', 'valamit inni', 10, 4), ('jung', 'fiatal', 3, 4), ('bleiben', 'maradni', 1, 4), ('das Abenteuer-', 'kaland', 0, 4), ('beginnen', 'elkezdeni', 1, 4), ('der Flughafen-:', 'repülőtér', 0, 4), ('mit dem Zug fahren', 'vonattal utazni', 10, 4), ('der Koffer-', 'bőrönd', 0, 4), ('der Rucksack-:e', 'hátizsák', 0, 4), ('überall', 'mindenhol', 4, 4), ('das Wort-:er', 'szó', 0, 4),
	('das Schild-er', 'címke,tábla,címer', 0, 4), ('etwas denken', 'gondolni vmit', 10, 4), ('lachen', 'nevetni', 1, 4), ('glücklich', 'boldog', 3, 4), ('kaufen', 'vásárolni', 1, 4), ('der Hunger', 'éhség', 0, 4), ('rufen', 'ordítani', 1, 4), ('schnell', 'gyors', 3, 4), ('der Bahnhof-:e', 'vonat állomás', 0, 4), ('finden', 'találni', 1, 4), ('die Fahrkarte-n', 'jegy', 0, 4), ('der Sitzplatz-:e', 'ülőhely', 0, 4), ('Recht haben', 'igaza van',10, 4), ('Tut mir leid!', 'Bocsánat!', 10, 4), ('glauben', 'hinni', 1, 4), ('manchmal', 'néha', 4, 4), ('seit', 'valami óta', 4, 4), ('der Monat-e', 'hónap', 0, 4), ('der Spaß', 'móka, szórakozás', 0, 4), ('fast', 'majdnem', 4, 4), ('spielen', 'játszani', 1, 4), ('joggen', 'kocogni', 1, 4), ('müssen', 'muszáj', 1, 4), ('Herzlich willkommen!', 'Üdvözöllek!', 10, 4), ('der Himmel', 'égbolt', 0, 4), ('scheinen', 'süt(pl a nap)', 1, 4), ('plötzlich', 'hirtelen', 3, 4), ('die Stimme-n', 'hang', 0, 4), ('Freut mich!', 'Örülök a találákozásnak!', 10, 4), ('die Reise-n', 'utazás', 0, 4), ('der Garten-:', 'kert', 0, 4), ('die Blume-n', 'virág', 0, 4), ('sitzen', 'ülni',1, 4), ('draußen', 'kint', 4, 4), ('der Kellner-s', 'pincér', 0, 4), ('die Kellnerin-nen', 'pincérnő', 0, 4), ('toll', 'nagyszerű', 3, 4), ('bestellen', 'rendelni', 1, 4), ('das Stück-e', 'darab', 0, 4), ('die Speisekarte-n', 'menü', 0, 4), ('lecker', 'finom', 3, 4), ('dass', 'az', 7, 4), ('das Obst', 'gyümölcs', 0, 4), ('Schau mal!', 'Nézd!', 10, 4), ('das Getränk-e', 'ital', 0, 4), ('das Fleugzeug-e', 'repülő', 0, 4), ('die Uhr-en' , 'óra', 0, 4), ('kaputt', 'elromlott', 3, 4), ('bezahlen', 'fizetni', 1, 4), ('der Nachmittag-e', 'délután', 0, 4), ('gestern', 'tegnap', 4, 4), ('das Bett-en', 'ágy',0, 4), ('das Zimmer-', 'szoba', 0, 4), ('der Balkon-e', 'erkély', 0, 4), ('normalerweise', 'általában', 4, 4), ('das Schlafzimmer-e', 'hálószoba', 0, 4), ('die Mitbewohnerin-nen', 'lakótárs(lány)', 0, 4), ('der Mitbewohner-', 'lakótárs', 0, 4), ('hell', 'világos(pl szoba)', 3, 4), ('das Abendessen', 'vacsora', 0, 4), ('schneiden', 'vágni', 1, 4), ('die Kerze-n', 'gyertya', 0, 4), 
('der Vorname-n', 'keresztnév', 0, 4), ('der Nachname-n', 'család,vezetéknév', 0, 4), ('das Amt-:er', 'hivatal', 0, 4), ('der Dialog-e', 'párbeszéd', 0, 4), ('das Heimatland-:er', 'haza(ország)', 0, 4), ('die Postleitzahl-en', 'irányítószám', 0, 4), ('die Reisepassnummer-n', 'útlevélszám', 0, 4), ('der Knoblauch-', 'fokhagyma', 0, 4), ('der Turnschuh-e', 'tornacipő', 0, 4), ('Ich laufe hin und her', 'Ide oda futkosok', 10, 4), ('Vorsicht!', 'Vigyázz!', 10, 4), ('Die Milch läuft über', 'Kifut a tej', 10, 4), ('Keine Bange!', 'Nyugi!', 10, 4);
