DELETE FROM words
WHERE lektion_num = 2;



INSERT INTO WORDS(german, hungarian, word_type_id, lektion_num)
VALUES ('sofort', 'azonnal', 4, 2), ('das Café-s', 'kávézó', 0, 2),('diskutieren', 'diskurálni', 1, 2), ('der Ausländer-', 'külföldi',0, 2), ('trinken', 'inni', 1, 2), ('der Tee-s', 'tea', 0, 2), ('der Kaffee-s', 'kávé', 0, 2), ('Guten Tag!', 'Jó napot!', 10, 2), 
('Entschuldigung!', 'Elnézést!', 10, 2), ('der Platz-:e', 'hely', 0, 2), ('hier', 'itt', 4, 2), ('frei', 'szabad', 3, 2), ('Wie?', 'Hogy? Hogyan? Milyen?', 4,2), ('also', 'tehát', 4, 2), ('noch einmal', 'mégegyszer', 10, 2), ('verstehen', 'megérteni', 1, 2), ('nichts', 'semmi', 2, 2), ('der Lärm', 'lárma', 0, 2), ('so', 'olyan,annyira, úgy', 7, 2), ('taub', 'süket', 3, 2), ('Arabien', 'Arábia', 0, 2), ('genau', 'pontosan', 3, 2), ('der Gastarbeiter-', 'vendégmunkás', 0, 2), ('der Elektrotechniker-', 'elektrotechnikus', 0, 2), ('bei', '-nál, -nél', 6, 2), ('Woher?', 'Honnan?', 4, 2), ('Was?', 'Mi?', 4, 2), ('machen', 'csinálni', 1, 2), ('arbeiten', 'dolgozni', 1, 2), ('als', 'mint, -ként', 7, 2), ('der Vater-:', 'apa', 0, 2), ('auch', 'is, szintén', 4, 2), ('der Ingenieur-e', 'mérnök', 0, 2), ('der Großvater-:', 'nagyapa', 0, 2), ('der Urgroßvater-:', 'dédapa', 0, 2), ('ebenso', 'ugyanúgy', 4, 2), ('nur', 'csak',4, 2), ('der Leichenbestatter-', 'temetkezésivállalkozó', 0, 2),
	('komisch', 'furcsa', 4, 2),('Wo?', 'Hol?', 4, 2), ('jetzt', 'most', 4, 2), ('verdienen', 'keresni(pénzt)', 1, 2), ('haben+A', 'birtokolni', 1 , 2), ('viel', 'sok', 4, 2), ('das Geld-er', 'pénz', 0, 2), ('wirklich', 'valóban', 3, 2), ('das Haus-:er', 'ház', 0, 2), ('das Einfamilienhaus-:er', 'családiház', 0, 2), ('nicht schlecht', 'nem rossz', 10, 2), ('das Kind-er', 'gyerek', 0, 2), ('zu Hause', 'otthon', 10, 2), ('gratulieren', 'gratulálni', 1, 2), ('dazu', 'hozzá, ahhoz',4, 2), ('Wann?', 'Mikor?', 4, 2), ('gehen', 'menni', 1, 2), ('wieder', 'megint, újra', 4, 2), ('nach Hause', 'haza(fele)', 10, 2), ('vielleicht', 'talán', 4, 2), ('nämlich', 'ugyanis', 4, 2), ('wenig', 'kevés', 4, 2), ('die Freizeit', 'szabadidő', 0, 2), ('die Arbeit-en', 'munka', 0, 2), ('noch', 'még', 4, 2), ('spazieren', 'sétálni', 1, 2), ('gern', 'szívesen', 4, 2), ('allein', 'egyedül', 3, 2), ('dann', 'akkor', 4, 2), ('zusammen', 'eggyütt', 4, 2), ('die Zeit-en', 'idő', 0, 2), ('das Echo-s', 'visszhang', 0, 2), ('sagen', 'mondani', 1, 2), ('der Prinz-en', 'herceg', 0, 2), ('aufs Geratewohl', 'találomra', 10, 2), ('antworten', 'felelni', 1, 2), ('fragen', 'kérdezni', 1, 2), ('Seid!', 'Legyetek!', 10, 2), ('der Freund-e', 'barát', 0, 2), ('die Freundin-nen', 'barátnő', 0, 2),('Wie bitte?', 'Hogyan kérem?', 10, 2), ('Was sind Sie von Beruf?', 'Mi az ön foglalkozása?', 10, 2), ('Nicht wahr?', 'Nemde?, Nem igaz?', 10, 2), ('Ach so!', 'Ja úgy!', 10, 2), ('In der Nähe', 'a közelben', 10, 2), ('nächstes Jahr', 'jövőre', 10, 2), ('Ich habe viel zu tun', 'Sok a dolgom', 10, 2),('der Arzt-:e', 'orvos', 0, 2), ('die Ärztin-nen', 'orvos(nő)', 0, 2), ('der Koch-:e', 'szakács', 0, 2), ('die Köchin-nen', 'szakácsnő', 0, 2), ('der Bäcker-', 'pék', 0, 2), ('die Bäckerin-nen', 'pék(nő)', 0, 2), ('der Lehrer-', 'tanár', 0, 2), ('die Lehrerin-nen', 'tanárnő', 0, 2), ('der Kauffmann-leute', 'kereskedő', 0, 2), ('die Kauffrau-en', 'kereskedőasszony', 0, 2), ('der Sekretär-e', 'titkár', 0, 2), ('die Sekretärin-nen', 'titkárnő', 0, 2), ('die Hausfrau-en', 'háziasszony', 0, 2), ('der Verkäufer-', 'eladó', 0, 2), ('die Verkäuferin-nen', 'eladónő', 0,2), ('der Fahrer-', 'vezető', 0, 2), ('die Fahrerin-nen', 'vezető(nő)', 0, 2), ('der Bauer-n', 'paraszt', 0, 2), ('die Bauerin-nen', 'paraszt(nő)', 0, 2), ('der Schüler-', 'tanuló', 0, 2), ('die Schülerin-nen', 'tanuló(lány)', 0, 2), ('der Student-en', 'tanuló(egyetemi)', 0, 2), ('die Studentin-nen', 'tanuló(lány, egyetemi)', 0, 2), ('die Bundesrepublik Deutschland', 'Német Szövetségi Köztársaság', 0, 2), ('liegen', 'fekszik,elhelyezkedik', 1, 2), ('Mitteleuropa', 'Közép-Európa', 0, 2), ('das Bundesland-:er', 'szövetségi tagállam', 0, 2), ('die Europäische Union', 'Európai Unió', 0, 2), ('die Haupstadt', 'főváros', 0, 2), ('das Nachbarland-:er', 'szomszédos ország', 0, 2), ('im Norden', 'északon', 10, 2), ('im Osten', 'keleten', 10, 2), ('im Süden', 'délen', 10, 2), 
('im Westen','nyugaton', 10, 2), ('der Fluss-:e', 'folyó', 0, 2), ('die Donau', 'Duna', 10, 2), ('miteinander', 'egymással',2, 2),('der Mann-:er', 'férfi', 0, 2);
